### ISSUE TITLE
Attribute position voor Layered Navigation synct niet naar Magento

### ISSUE THREAD

**Issue by Kniremijer** [NVision-Commerce-Solutions/Commerce365.Core.Public#4]
Magento:
![image](https://user-images.githubusercontent.com/98964642/152502132-caf300f4-6bbf-4883-a00b-cce2530db37e.png)

Commerce 365:
![image](https://user-images.githubusercontent.com/98964642/152502344-f5677b2e-1d87-4342-badb-98b2f45be77e.png)

Sync Log van attribute
{
  "scope": 0,
  "default_frontend_label": "Hout type",
  "frontend_input": "select",
  "is_required": false,
  "attribute_code": "f_houttype",
  "is_unique": "0",
  "is_used_in_grid": false,
  "is_filterable_in_grid": true,
  "is_searchable": "1",
  "is_visible_in_advanced_search": "1",
  "is_comparable": "1",
  "is_filterable": true,
  "is_filterable_in_search": true,
  "position": 1,
  "is_used_for_promo_rules": "0",
  "is_html_allowed_on_front": false,
  "is_visible_on_front": "1",
  "used_in_product_listing": "0",
  "default_value": "",
  "is_visible": true
}

**Comment by TysvdHeuvel** [comment]
Fixed
